version: '3'

services:
  shome-scene-processor:
    image: "${IMAGE_PREFIX}shome.scene.processor:${TAG}"
    environment:
      MqttConfig__Host: "192.168.1.1"
      MqttConfig__Port: 1883
      MqttConfig__User: ""
      MqttConfig__Password: ""
      Logging__LogLevel__Default: "Warning"
      Logging__LogLevel__Akka: "Information"
    volumes:
      - "/home/docker/shome.scene/scenes:/app/scenes"
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3